;this file for FamiTone2 library generated by FamiStudio

;.if FAMISTUDIO_CFG_C_BINDINGS
;.export _castle_escape_music_data=castle_escape_music_data
;.endif

castle_escape_music_data:
	.byte 3
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256

.export castle_escape_music_data
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $b0 ;instrument 00 (Bass)
	.word @env5, @env0, @env0
	.byte $00
	.byte $30 ;instrument 01 (GBA Snare (8-#))
	.word @env3, @env8, @env0
	.byte $00
	.byte $b0 ;instrument 02 (Harpsichord-Alt1)
	.word @env10, @env0, @env0
	.byte $00
	.byte $30 ;instrument 03 (NoiseBassDrum)
	.word @env4, @env2, @env0
	.byte $00
	.byte $30 ;instrument 04 (NoiseCymbal)
	.word @env1, @env7, @env0
	.byte $00
	.byte $30 ;instrument 05 (NoiseHiHat)
	.word @env6, @env9, @env0
	.byte $00

@samples:
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $ca,$c6,$c3,$c0,$00,$03
@env2:
	.byte $c0,$bf,$c1,$00,$02
@env3:
	.byte $cf,$c6,$cd,$c9,$c7,$c5,$c3,$c2,$c1,$02,$c0,$00,$0a
@env4:
	.byte $cf,$cd,$c6,$c4,$c3,$c0,$00,$05
@env5:
	.byte $cf,$7f,$00,$00
@env6:
	.byte $ca,$ca,$c7,$c6,$c6,$c5,$04,$c4,$c3,$c2,$c1,$05,$c0,$00,$0c
@env7:
	.byte $c0,$c1,$c2,$00,$02
@env8:
	.byte $b9,$c0,$00,$01
@env9:
	.byte $c0,$c1,$03,$c2,$c1,$c2,$c1,$c2,$c1,$c2,$00,$09
@env10:
	.byte $c7,$c6,$c5,$c5,$c4,$c4,$c3,$00,$06
@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@song0ref4:
	.byte $f9, $f9, $f9, $91, $f9, $f9, $f9, $91, $f9, $f9, $f9, $91, $f9, $f9, $f9, $91, $f9, $f9, $f9, $91, $f9, $f9, $f9, $91
	.byte $f9, $f9, $f9, $91, $f9, $f9, $f9, $91, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $f9, $f9, $f9, $91, $f9, $f9, $f9, $91, $f9, $f9, $f9, $91, $f9, $f9, $f9, $91, $84
@song0ref57:
	.byte $4a, $93, $00, $32, $93, $00, $32, $93, $00, $4a, $93, $00, $32, $93, $00, $32, $93, $00, $4a, $93, $00, $32
@song0ref79:
	.byte $93, $00, $4e, $93, $00, $36, $93, $00, $36, $93, $00, $4e, $93, $00, $36, $93, $00, $36, $93, $00, $4e, $93, $00, $36
	.byte $93, $00, $52, $93, $00, $3a, $93, $00, $3a, $93, $00, $52, $93, $00, $3a, $93, $00, $3a, $93, $00, $52, $93, $00, $3a
	.byte $ff, $1a
	.word @song0ref79
	.byte $ff, $46
	.word @song0ref57
	.byte $93, $00, $54, $93, $00, $3c, $93, $00, $3c, $93, $00, $54, $93, $00, $3c, $93, $00, $3c, $93, $00, $54, $93, $00, $3c
	.byte $93, $00, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref164:
	.byte $1a, $95, $1e, $8f, $00, $83, $1e, $8f, $00, $83, $1a, $95, $1e, $8f, $00, $83, $1e, $8f, $00, $b3, $1a, $95, $1e, $8f
	.byte $00, $83, $1e, $8f, $00, $83, $1a, $95, $1e, $8f, $00, $83, $1e, $8f, $00, $83, $24, $a7, $00, $83
	.byte $ff, $28
	.word @song0ref164
	.byte $28, $a7, $00, $83
	.byte $ff, $2c
	.word @song0ref164
	.byte $ff, $28
	.word @song0ref164
	.byte $28, $a7, $00, $83
	.byte $ff, $2c
	.word @song0ref164
	.byte $ff, $28
	.word @song0ref164
	.byte $28, $a7, $00, $83
	.byte $ff, $2c
	.word @song0ref164
	.byte $ff, $28
	.word @song0ref164
	.byte $28, $a7, $00, $83, $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $f9, $f9, $f9, $91, $f9, $f9, $f9, $91
@song0ref257:
	.byte $82, $54, $ad, $86, $48, $95, $48, $95, $00, $95, $82, $54, $95, $86, $48, $95, $48, $95, $82, $54, $ad, $86, $48, $95
	.byte $48, $95, $00, $95, $82, $54, $95, $86, $48, $95, $48, $95
	.byte $ff, $1c
	.word @song0ref257
	.byte $ff, $1c
	.word @song0ref257
	.byte $ff, $1c
	.word @song0ref257
	.byte $ff, $1c
	.word @song0ref257
	.byte $ff, $1c
	.word @song0ref257
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $20
	.word @song0ref4
	.byte $fd
	.word @song0ch4loop
@song1ch0:
	.byte $fb, $01
@song1ref3:
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb
@song1ch0loop:
	.byte $ff, $0c
	.word @song1ref3
	.byte $fd
	.word @song1ch0loop
@song1ch1:
	.byte $ff, $0c
	.word @song1ref3
@song1ch1loop:
	.byte $84
@song1ref27:
	.byte $1a, $8f, $00, $1a, $8f, $00, $32, $8f, $00, $32, $8f, $00, $1a, $8f, $00, $1a, $8f, $00, $32, $91, $32, $8f, $00
	.byte $ff, $17
	.word @song1ref27
@song1ref53:
	.byte $1e, $8f, $00, $1e, $8f, $00, $36, $8f, $00, $36, $8f, $00, $1e, $8f, $00, $1e, $8f, $00, $36, $91, $36, $8f, $00
	.byte $ff, $17
	.word @song1ref53
@song1ref79:
	.byte $20, $8f, $00, $20, $8f, $00, $38, $8f, $00, $38, $8f, $00, $20, $8f, $00, $20, $8f, $00, $38, $91, $38, $8f, $00
	.byte $ff, $17
	.word @song1ref79
	.byte $24, $8f, $00, $24, $8f, $00, $3c, $8f, $00, $3c, $8f, $00, $24, $8f, $00, $24, $8f, $00, $3c, $91, $3c, $8f, $00, $28
	.byte $8f, $00, $28, $8f, $00, $40, $8f, $00, $40, $8f, $00, $16, $8f, $00, $16, $8f, $00, $2e, $91, $2e, $8f, $00, $fd
	.word @song1ch1loop
@song1ch2:
@song1ref154:
	.byte $80, $4a, $f9, $f9, $c9, $4e, $f9, $f9, $c9, $50, $f9, $f9, $c9, $54, $f9, $a3, $58, $cd, $46, $cd
@song1ch2loop:
	.byte $ff, $13
	.word @song1ref154
	.byte $fd
	.word @song1ch2loop
@song1ch3:
@song1ref181:
	.byte $86, $5a, $91, $5a, $91, $82, $50, $91, $50, $91, $86, $5a, $91, $5a, $91, $82, $50, $91, $00, $91
	.byte $ff, $10
	.word @song1ref181
	.byte $ff, $10
	.word @song1ref181
	.byte $ff, $10
	.word @song1ref181
	.byte $ff, $10
	.word @song1ref181
	.byte $ff, $10
	.word @song1ref181
	.byte $ff, $10
	.word @song1ref181
	.byte $ff, $10
	.word @song1ref181
@song1ch3loop:
	.byte $ff, $10
	.word @song1ref181
	.byte $ff, $10
	.word @song1ref181
	.byte $ff, $10
	.word @song1ref181
	.byte $ff, $10
	.word @song1ref181
	.byte $ff, $10
	.word @song1ref181
	.byte $ff, $10
	.word @song1ref181
	.byte $ff, $10
	.word @song1ref181
	.byte $ff, $10
	.word @song1ref181
	.byte $fd
	.word @song1ch3loop
@song1ch4:
	.byte $ff, $0c
	.word @song1ref3
@song1ch4loop:
	.byte $ff, $0c
	.word @song1ref3
	.byte $fd
	.word @song1ch4loop
@song2ch0:
	.byte $fb, $01
@song2ch0loop:
	.byte $f9, $f9, $f9, $91, $fd
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $f9, $f9, $f9, $91, $fd
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $f9, $f9, $f9, $91, $fd
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
@song2ref28:
	.byte $88, $5a, $89, $82, $5a, $89, $5a, $89, $88, $5a, $89, $82, $5a, $89, $5a, $89, $88, $5a, $89, $82, $5a, $89
	.byte $ff, $10
	.word @song2ref28
	.byte $ff, $10
	.word @song2ref28
	.byte $8a, $58, $89, $82, $5a, $89, $5a, $89, $8a, $58, $89, $82, $5a, $89, $5a, $89, $8a, $5a, $89, $56, $89, $fd
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $f9, $f9, $f9, $91, $fd
	.word @song2ch4loop
