;this file for FamiTone2 libary generated by FamiStudio

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_0_sword_slash
	.word @sfx_ntsc_1_star_collect

@sfx_ntsc_0_sword_slash:
	.byte $8a,$0f,$89,$3f,$8a,$0e,$01,$8a,$0d,$01,$8a,$0c,$01,$8a,$0b,$01
	.byte $8a,$0a,$01,$8a,$09,$01,$8a,$08,$01,$8a,$07,$01,$8a,$06,$00
@sfx_ntsc_1_star_collect:
	.byte $82,$00,$81,$bd,$80,$3f,$89,$f0,$81,$7e,$01,$81,$54,$80,$36,$01
	.byte $80,$3d,$01,$80,$39,$01,$80,$37,$01,$80,$35,$01,$80,$33,$01,$80
	.byte $32,$01,$80,$31,$03,$00
