;this file for FamiTone2 library generated by FamiStudio

kirbys_adv_boss_theme_cover_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument 00 (bass_sq1)
	.word @env1, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 01 (intro3)
	.word @env10, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 02 (introsq1)
	.word @env3, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 03 (introsq2)
	.word @env6, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 04 (introsq2_dlugie)
	.word @env7, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 05 (melo1_sq1)
	.word @env11, @env0, @env0
	.byte $00
	.byte $30 ;instrument 06 (melo2_sq1)
	.word @env4, @env0, @env0
	.byte $00
	.byte $30 ;instrument 07 (per1)
	.word @env9, @env0, @env0
	.byte $00
	.byte $30 ;instrument 08 (per2)
	.word @env2, @env0, @env0
	.byte $00
	.byte $30 ;instrument 09 (per3)
	.word @env5, @env0, @env0
	.byte $00
	.byte $30 ;instrument 0a (trojkat_krotki)
	.word @env8, @env0, @env0
	.byte $00

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;1 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;2 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;3 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;4 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;5 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;6 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;7 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;8 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;9 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;10 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;11 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;12 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;13 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;14 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;15 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;16 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;17 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;18 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;19 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;20 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;21 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;22 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;23 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;24 
	.byte $00+.lobyte(FT_DPCM_PTR),$0b,$0f	;25 (kirby_kick.dmc)
	.byte $00+.lobyte(FT_DPCM_PTR),$0b,$0e	;26 (kirby_kick.dmc)
	.byte $09+.lobyte(FT_DPCM_PTR),$1c,$0f	;27 (kirby_snare.dmc)
	.byte $06+.lobyte(FT_DPCM_PTR),$0b,$0f	;28 (kirby_puk.dmc)
	.byte $06+.lobyte(FT_DPCM_PTR),$0b,$0e	;29 (kirby_puk.dmc)
	.byte $03+.lobyte(FT_DPCM_PTR),$0a,$0f	;30 (kirby_pik.dmc)
	.byte $11+.lobyte(FT_DPCM_PTR),$18,$08	;31 (roar)
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;32 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;33 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;34 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;35 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;36 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;37 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;38 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;39 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;40 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;41 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;42 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;43 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;44 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;45 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;46 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;47 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;48 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;49 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;50 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;51 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;52 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;53 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;54 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;55 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;56 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;57 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;58 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;59 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;60 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;61 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;62 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;63 

@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $c6,$c6,$c4,$c3,$c0,$00,$04
@env2:
	.byte $c5,$c2,$c0,$00,$02
@env3:
	.byte $cf,$03,$c4,$c4,$c0,$00,$04
@env4:
	.byte $c8,$c6,$c6,$c0,$00,$03
@env5:
	.byte $cb,$c8,$c6,$c4,$c0,$00,$04
@env6:
	.byte $cf,$ce,$cd,$cc,$c4,$c4,$c0,$00,$06
@env7:
	.byte $cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c8,$c4,$02,$c0,$00,$0b
@env8:
	.byte $cf,$03,$c0,$00,$02
@env9:
	.byte $cd,$ca,$c8,$c6,$c4,$c2,$c0,$00,$06
@env10:
	.byte $cf,$cd,$02,$c0,$00,$03
@env11:
	.byte $c5,$c3,$02,$c0,$00,$03

@song0ch0:
@ref0:
	.byte $84,$28,$1e,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$87
@ref1:
	.byte $81,$82,$46,$46,$87,$46,$46,$8d
@ref2:
	.byte $83
@song0ch0loop:
@ref3:
	.byte $80,$38,$32,$8a,$40,$80,$38,$32,$8a,$44,$80,$38,$32,$8a,$46,$80,$38,$32,$8a,$44,$80,$38,$32,$8a,$40,$80,$38
@ref4:
	.byte $38,$32,$8a,$40,$80,$38,$32,$8a,$44,$80,$38,$32,$8a,$46,$80,$38,$32,$8a,$44,$80,$38,$32,$8a,$40,$80,$38
@ref5:
	.byte $34,$2e,$8a,$3c,$80,$34,$2e,$8a,$40,$80,$34,$2e,$8a,$42,$80,$34,$2e,$8a,$40,$80,$34,$2e,$8a,$3c,$80,$34
	.byte $ff,$10
	.word @ref5
	.byte $ff,$10
	.word @ref4
	.byte $ff,$10
	.word @ref4
	.byte $ff,$10
	.word @ref5
	.byte $ff,$10
	.word @ref5
@ref6:
	.byte $8c,$48,$3c,$36,$48,$3c,$36,$48,$3c,$36,$28,$48,$46,$48,$40,$28,$48
@ref7:
	.byte $4c,$40,$3a,$4c,$40,$3a,$4c,$40,$3a,$2c,$4c,$4a,$4c,$44,$2c,$4c
@ref8:
	.byte $4e,$42,$3c,$4e,$42,$3c,$4e,$42,$3c,$2e,$4e,$4c,$4e,$46,$2e,$4e
@ref9:
	.byte $50,$44,$3e,$50,$44,$3e,$50,$44,$3e,$30,$50,$4e,$50,$48,$30,$50
@ref10:
	.byte $48,$3c,$36,$48,$3c,$36,$48,$3c,$36,$28,$48,$46,$48,$40,$28,$48
	.byte $ff,$10
	.word @ref7
@ref11:
	.byte $46,$3a,$34,$46,$3a,$34,$46,$3a,$34,$26,$46,$44,$46,$3e,$26,$46
@ref12:
	.byte $48,$3c,$36,$48,$3c,$36,$48,$3c,$36,$3c,$44,$4a,$48,$58,$4e,$40
	.byte $fd
	.word @song0ch0loop

@song0ch1:
	.byte $fb, $06
@ref13:
	.byte $86,$28,$1e,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$12,$14,$fb,$04,$16,$14
@ref14:
	.byte $12,$fb,$06,$82,$30,$30,$86,$10,$11,$10,$82,$30,$30,$86,$10,$11,$10,$fb,$04,$88,$10,$83
@ref15:
	.byte $fb,$06,$86,$1e,$10
@song0ch1loop:
@ref16:
	.byte $fb,$06,$88,$03,$29,$11,$28,$1b,$03,$28,$11,$28,$81
@ref17:
	.byte $03,$29,$11,$28,$1b,$03,$28,$11,$1a,$18
@ref18:
	.byte $03,$25,$0d,$24,$17,$03,$24,$0d,$24,$81
@ref19:
	.byte $03,$25,$0d,$24,$17,$03,$24,$0d,$16,$18
@ref20:
	.byte $fb,$06,$03,$29,$11,$28,$1b,$03,$28,$11,$28,$81
	.byte $ff,$0a
	.word @ref17
	.byte $ff,$0a
	.word @ref18
	.byte $ff,$0a
	.word @ref19
@ref21:
	.byte $86,$28,$10,$10,$28,$10,$10,$28,$10,$10,$10,$28,$10,$28,$10,$10,$12
@ref22:
	.byte $2c,$14,$14,$2c,$14,$14,$2c,$14,$14,$14,$2c,$14,$2c,$14,$14,$16
@ref23:
	.byte $2e,$16,$16,$2e,$16,$16,$2e,$16,$16,$16,$2e,$16,$2e,$16,$16,$18
@ref24:
	.byte $30,$18,$18,$30,$18,$18,$30,$18,$18,$18,$30,$18,$30,$18,$18,$1a
@ref25:
	.byte $28,$10,$10,$28,$10,$10,$28,$10,$10,$10,$28,$10,$28,$10,$10,$12
	.byte $ff,$10
	.word @ref22
@ref26:
	.byte $26,$0e,$0e,$26,$0e,$0e,$26,$0e,$0e,$0e,$26,$0e,$26,$0e,$0e,$10
@ref27:
	.byte $28,$10,$10,$28,$10,$10,$28,$10,$10,$10,$28,$10,$28,$12,$fb,$04,$02,$02
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref28:
	.byte $9f
@ref29:
	.byte $81,$94,$54,$54,$87,$54,$54,$8d
@ref30:
	.byte $83
@song0ch2loop:
@ref31:
	.byte $94,$62,$4a,$50,$4a,$62,$54,$4a,$4a,$58,$4a,$4a,$54,$62,$4a,$50,$4a
@ref32:
	.byte $62,$4a,$50,$4a,$62,$54,$4a,$4a,$58,$4a,$4a,$54,$62,$4a,$50,$4a
@ref33:
	.byte $5e,$46,$4c,$46,$5e,$50,$46,$46,$54,$46,$46,$50,$5e,$46,$4c,$46
	.byte $ff,$10
	.word @ref33
	.byte $ff,$10
	.word @ref32
	.byte $ff,$10
	.word @ref32
	.byte $ff,$10
	.word @ref33
	.byte $ff,$10
	.word @ref33
@ref34:
	.byte $4e,$4e,$40,$40,$4e,$4e,$40,$40,$4e,$4e,$40,$40,$4e,$4e,$40,$40
@ref35:
	.byte $52,$52,$44,$44,$52,$52,$44,$44,$52,$52,$44,$44,$52,$52,$44,$44
@ref36:
	.byte $54,$54,$46,$46,$54,$54,$46,$46,$54,$54,$46,$46,$54,$54,$46,$46
@ref37:
	.byte $56,$56,$48,$48,$56,$56,$48,$48,$56,$56,$48,$48,$58,$5e,$5c,$5a
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref35
@ref38:
	.byte $4c,$4c,$3e,$3e,$4c,$4c,$3e,$3e,$4c,$4c,$3e,$3e,$4c,$4c,$3e,$3e
@ref39:
	.byte $4e,$4e,$40,$40,$4e,$4e,$40,$40,$4e,$4e,$40,$40,$4a,$50,$4e,$4c
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref40:
	.byte $9f
@ref41:
	.byte $81,$8e,$58,$58,$5e,$5e,$83,$58,$58,$5e,$5e,$83,$90,$5a,$83
@ref42:
	.byte $5c,$5c
@song0ch3loop:
@ref43:
	.byte $92,$5a,$5c,$5c,$5a,$5a,$5c,$5c,$5a,$5a,$5c,$5c,$5a,$5a,$5c,$5c,$5a
@ref44:
	.byte $5a,$5c,$5c,$5a,$5a,$5c,$5c,$5a,$5a,$5c,$5c,$5a,$5a,$5c,$5c,$5a
	.byte $ff,$10
	.word @ref44
	.byte $ff,$10
	.word @ref44
	.byte $ff,$10
	.word @ref44
	.byte $ff,$10
	.word @ref44
	.byte $ff,$10
	.word @ref44
	.byte $ff,$10
	.word @ref44
@ref45:
	.byte $56,$5c,$5a,$5c,$56,$5c,$5a,$5c,$56,$5c,$5a,$5c,$56,$5c,$5a,$5c
	.byte $ff,$10
	.word @ref45
	.byte $ff,$10
	.word @ref45
	.byte $ff,$10
	.word @ref45
	.byte $ff,$10
	.word @ref45
	.byte $ff,$10
	.word @ref45
	.byte $ff,$10
	.word @ref45
	.byte $ff,$10
	.word @ref45
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref46:
	.byte $36,$36,$36,$36,$36,$36,$36,$36,$36,$36,$37,$36,$37,$36
@ref47:
	.byte $81,$36,$36,$32,$33,$34,$36,$36,$32,$33,$34,$36,$36,$36
@ref48:
	.byte $32,$36
@song0ch4loop:
@ref49:
	.byte $32,$38,$3c,$32,$37,$3a,$3a,$32,$38,$3c,$32,$37,$3a,$3a
@ref50:
	.byte $32,$38,$3c,$32,$37,$3a,$3a,$3a,$38,$3c,$38,$36,$3c,$3a,$3a
	.byte $ff,$0e
	.word @ref49
	.byte $ff,$0f
	.word @ref50
	.byte $ff,$0e
	.word @ref49
	.byte $ff,$0f
	.word @ref50
	.byte $ff,$0e
	.word @ref49
@ref51:
	.byte $32,$38,$3c,$32,$37,$3a,$3a,$38,$3c,$36,$32,$36,$32,$3a,$32
@ref52:
	.byte $33,$38,$32,$37,$3b,$33,$39,$36,$32,$3a,$3c
@ref53:
	.byte $33,$39,$37,$3a,$32,$32,$32,$39,$36,$32,$36,$36
	.byte $ff,$0b
	.word @ref52
	.byte $ff,$0c
	.word @ref53
	.byte $ff,$0b
	.word @ref52
	.byte $ff,$0c
	.word @ref53
	.byte $ff,$0b
	.word @ref52
	.byte $ff,$0c
	.word @ref53
	.byte $fd
	.word @song0ch4loop
