#define DECKSWABBER_CODE_BANK 3
#define DECKSWABBER_METASPRITE_BANK 3

#define DECKSWABBER_TILE_HEIGHT 8
#define DECKSWABBER_TILE_WIDTH 8

#define DECKSWABBER_LEVEL_PACK_SIZE 10

#define DECKSWABBER_HEALTHBAR_FULL_TILE 0xF6
#define DECKSWABBER_HEALTHBAR_PART_TILE 0xF7

// Assumes an original-style 8 by 8 grid... will need to use something else if we want alternate grid sizes
#define DeckswabberGetTileIndex(destinationVar, x_coord, y_coord) { \
    __asm__("lda %v", y_coord); \
    __asm__("asl"); \
    __asm__("asl"); \
    __asm__("asl"); \
    __asm__("ora %v", x_coord); \
    __asm__("sta %v", destinationVar); \
};

#define DECKSWABBER_WATER_HOLE_ID (sizeof(deckswabber_metatiles)/5 - 2)
#define DECKSWABBER_EMPTY_HOLE_ID (sizeof(deckswabber_metatiles)/5 - 1)

#define DECKSWABBER_MAX_ONSCREEN_ENTITIES 7

#define DECKSWABBER_ENTITY_ID_CURTAIN 0
#define DECKSWABBER_ENTITY_ID_EXPLOSION 1
#define DECKSWABBER_ENTITY_ID_COIN_BRONZE 2
#define DECKSWABBER_ENTITY_ID_COIN_SILVER 3
#define DECKSWABBER_ENTITY_ID_COIN_GOLD 4
#define DECKSWABBER_ENTITY_ID_CHEST_BRONZE 5
#define DECKSWABBER_ENTITY_ID_CHEST_SILVER 6
#define DECKSWABBER_ENTITY_ID_CHEST_GOLD 7
#define DECKSWABBER_ENTITY_ID_SWORD 8
#define DECKSWABBER_ENTITY_ID_FLAG_HALF 9
#define DECKSWABBER_ENTITY_ID_FLAG_FULL 10
#define DECKSWABBER_ENTITY_ID_DIRT_BOMB_PLUS 11
#define DECKSWABBER_ENTITY_ID_DIRT_BOMB_SQUARE 12
#define DECKSWABBER_ENTITY_ID_CANNON 13
#define DECKSWABBER_ENTITY_ID_MYNCI 14
#define DECKSWABBER_ENTITY_ID_TECHO 15
#define DECKSWABBER_ENTITY_ID_CAPTAIN_DREAD 16
// #define DECKSWABBER_ENTITY_ID_CAPTAIN_DREAD ??

// Flags that need to be cleared at the start of each frame...
#define DECKSWABBER_DID_SCORE_CHANGE_THIS_FRAME_MASK      0b00000001
#define DECKSWABBER_DID_HP_CHANGE_THIS_FRAME_MASK         0b00000010
#define DECKSWABBER_DID_DIRTBOMB_EXPLODE_THIS_FRAME_MASK  0b00000100

#define DECKSWABBER_RESET_PLAYER_FLAGS_START_FRAME() (player_flags &= ~(DECKSWABBER_DID_SCORE_CHANGE_THIS_FRAME_MASK | DECKSWABBER_DID_HP_CHANGE_THIS_FRAME_MASK | DECKSWABBER_DID_DIRTBOMB_EXPLODE_THIS_FRAME_MASK))

#define DECKSWABBER_SET_SCORE_CHANGED_THIS_FRAME()      (player_flags |= DECKSWABBER_DID_SCORE_CHANGE_THIS_FRAME_MASK)
#define DECKSWABBER_SET_HP_CHANGED_THIS_FRAME()         (player_flags |= DECKSWABBER_DID_HP_CHANGE_THIS_FRAME_MASK)
#define DECKSWABBER_SET_DIRTBOMB_EXPLODED_THIS_FRAME()  (player_flags |= DECKSWABBER_DID_DIRTBOMB_EXPLODE_THIS_FRAME_MASK)

#define DECKSWABBER_SCORE_CHANGED_THIS_FRAME            (player_flags & DECKSWABBER_DID_SCORE_CHANGE_THIS_FRAME_MASK)
#define DECKSWABBER_HP_CHANGED_THIS_FRAME               (player_flags & DECKSWABBER_DID_HP_CHANGE_THIS_FRAME_MASK)
#define DECKSWABBER_DIRTBOMB_EXPLODED_THIS_FRAME        (player_flags & DECKSWABBER_DID_DIRTBOMB_EXPLODE_THIS_FRAME_MASK)

// Flags that don't
#define DECKSWABBER_CAN_MAKE_HOSTILE_ENTITY_MASK        0b00001000
#define DECKSWABBER_CAN_MAKE_PASSIVE_ENTITY_MASK        0b00010000

#define DECKSWABBER_CAN_MAKE_HOSTILE_ENTITY             (player_flags & DECKSWABBER_CAN_MAKE_HOSTILE_ENTITY_MASK)
#define DECKSWABBER_SET_CAN_MAKE_HOSTILE_ENTITY()       (player_flags |= DECKSWABBER_CAN_MAKE_HOSTILE_ENTITY_MASK)
#define DECKSWABBER_RESET_CAN_MAKE_HOSTILE_ENTITY()     (player_flags &= ~DECKSWABBER_CAN_MAKE_HOSTILE_ENTITY_MASK)

#define DECKSWABBER_CAN_MAKE_PASSIVE_ENTITY             (player_flags & DECKSWABBER_CAN_MAKE_PASSIVE_ENTITY_MASK)
#define DECKSWABBER_SET_CAN_MAKE_PASSIVE_ENTITY()       (player_flags |= DECKSWABBER_CAN_MAKE_PASSIVE_ENTITY_MASK)
#define DECKSWABBER_RESET_CAN_MAKE_PASSIVE_ENTITY()     (player_flags &= ~DECKSWABBER_CAN_MAKE_PASSIVE_ENTITY_MASK)


#define DECKSWABBER_PLAYER_DEPTHMAP_MASK 0b10000000